language: go
go_import_path: github.com/hibiken/asynq
git:
  depth: 1
go: [1.13.x, 1.14.x]
script:
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
services:
  - redis-server
after_success:
  - bash ./.travis/benchcmp.sh
  - bash ./.travis/goreportcard.sh
  - bash <(curl -s https://codecov.io/bash)
